### ISSUE TITLE
Reporte de Practica

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-nuggets-de-pollo#1]
[Reporte de Mockup.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-nuggets-de-pollo/files/14727453/Reporte.de.Mockup.pdf)

**Comment by Irvingzr16** [comment]
https://www.figma.com/file/cyGXop2EScFy50x8cGjKgM/TimShop?type=design&node-id=0-1&mode=design&t=soCq3y4kDLXWZsMi-0

**Comment by saul19bautista** [comment]
Portada  25
procedimiento 25
firguras e ilustraciones: 25
resultado y conclusiones: 25


buen trabajo, todo bien estructurado 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
